version: '3.7'
services:
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./Backend/
      target: prod
    env_file:
      - ./Backend/src/config/.env
    expose:
      - 4000
    ports:
      -"4000:4000"
    command: "node build/index.js"
  database:
    image: mongo
    ports:
      - "27017:27017"
